/*
  # Add Themed Escape Rooms

  1. New Data
    - Adding 60+ escape rooms across 15 different themes
    - Each room includes title, theme, difficulty, location, duration, price, and description
    - Covers all major themes: Horror, Mystery, Sci-Fi, Adventure, Fantasy, Thriller, Historical, Crime, Zombie, Prison Break, Pirate, Space, Medieval, Steampunk, Western

  2. Data Structure
    - All rooms will have default values for missing fields
    - Rating set to 4.5 for all rooms
    - Max players set to 6 for all rooms
    - Sample what_to_expect and recent_reviews data
    - Default image URLs from Pexels
*/

-- Horror Theme Escape Rooms
INSERT INTO escape_rooms (title, theme, difficulty, location, duration, price_per_person, description, rating, max_players, what_to_expect, recent_reviews, image_url) VALUES
('Abandoned Asylum', 'Horror', 'Expert', 'Downtown', 75, 45.00, 'Escape the haunted psychiatric facility', 4.5, 6, '["Terrifying atmosphere", "Jump scares", "Psychological puzzles", "Immersive storyline"]', '[{"name": "Sarah M.", "rating": 5, "comment": "Absolutely terrifying! Best horror escape room ever."}, {"name": "Mike R.", "rating": 4, "comment": "Great scares and challenging puzzles."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Vampire''s Lair', 'Horror', 'Advanced', 'Historic District', 60, 40.00, 'Find the ancient artifact before sunrise', 4.5, 6, '["Gothic atmosphere", "Time pressure", "Hidden compartments", "Vampire lore"]', '[{"name": "Emma L.", "rating": 5, "comment": "Amazing vampire theme with great props!"}, {"name": "David K.", "rating": 4, "comment": "Challenging but fair puzzles."}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Zombie Laboratory', 'Horror', 'Medium', 'Industrial District', 50, 35.00, 'Survive the outbreak and find the cure', 4.5, 6, '["Zombie effects", "Laboratory setting", "Team cooperation", "Medical puzzles"]', '[{"name": "Alex P.", "rating": 4, "comment": "Great zombie theme with realistic props."}, {"name": "Lisa T.", "rating": 5, "comment": "Loved the scientific puzzles!"}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Haunted Manor', 'Horror', 'Hard', 'Uptown', 65, 42.00, 'Uncover the dark family secrets', 4.5, 6, '["Victorian setting", "Family mystery", "Ghostly encounters", "Hidden passages"]', '[{"name": "Tom W.", "rating": 5, "comment": "Incredible attention to detail in the manor."}, {"name": "Rachel S.", "rating": 4, "comment": "Spooky atmosphere throughout."}]', 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Demon''s Cathedral', 'Horror', 'Expert', 'University Area', 70, 48.00, 'Perform an exorcism before dawn', 4.5, 6, '["Religious horror", "Exorcism ritual", "Latin puzzles", "Supernatural elements"]', '[{"name": "Chris B.", "rating": 5, "comment": "Most intense horror experience ever!"}, {"name": "Amy F.", "rating": 4, "comment": "Great use of religious imagery."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Mystery Theme Escape Rooms
('Murder at the Opera', 'Mystery', 'Medium', 'Uptown', 65, 42.00, 'Solve the crime during intermission', 4.5, 6, '["Opera house setting", "Murder mystery", "Classical music", "Detective work"]', '[{"name": "Helen G.", "rating": 5, "comment": "Elegant mystery with great atmosphere."}, {"name": "Robert J.", "rating": 4, "comment": "Loved the opera house theme."}]', 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Detective''s Cold Case', 'Mystery', 'Advanced', 'Downtown', 70, 38.00, 'Crack the 20-year-old unsolved mystery', 4.5, 6, '["Cold case files", "Evidence analysis", "Timeline puzzles", "Detective office"]', '[{"name": "Mark D.", "rating": 4, "comment": "Great detective work required."}, {"name": "Susan H.", "rating": 5, "comment": "Felt like a real detective!"}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Art Gallery Heist', 'Mystery', 'Expert', 'Entertainment District', 80, 50.00, 'Recover the stolen masterpiece', 4.5, 6, '["Art gallery setting", "Heist theme", "Security systems", "Art history"]', '[{"name": "Jennifer L.", "rating": 5, "comment": "Sophisticated puzzles and beautiful setting."}, {"name": "Paul M.", "rating": 4, "comment": "Challenging but rewarding."}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Sherlock''s Study', 'Mystery', 'Medium', 'Business District', 55, 36.00, 'Solve Holmes'' final case', 4.5, 6, '["Victorian London", "Sherlock Holmes theme", "Deductive reasoning", "Classic mysteries"]', '[{"name": "Andrew C.", "rating": 5, "comment": "Perfect Sherlock Holmes experience!"}, {"name": "Maria R.", "rating": 4, "comment": "Great attention to Victorian details."}]', 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Missing Heir', 'Mystery', 'Hard', 'Tourist Area', 60, 40.00, 'Find the lost family fortune', 4.5, 6, '["Family secrets", "Inheritance mystery", "Hidden clues", "Genealogy puzzles"]', '[{"name": "Karen T.", "rating": 4, "comment": "Intriguing family mystery."}, {"name": "Steve N.", "rating": 5, "comment": "Loved the treasure hunt aspect."}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Sci-Fi Theme Escape Rooms
('Mars Colony Crisis', 'Sci-Fi', 'Advanced', 'Airport Area', 90, 55.00, 'Repair the life support systems', 4.5, 6, '["Mars colony setting", "Space technology", "Life support systems", "Futuristic puzzles"]', '[{"name": "Brian K.", "rating": 5, "comment": "Amazing sci-fi experience!"}, {"name": "Linda P.", "rating": 4, "comment": "Great use of technology."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Time Machine Malfunction', 'Sci-Fi', 'Expert', 'University Area', 85, 48.00, 'Fix the temporal anomaly', 4.5, 6, '["Time travel", "Temporal puzzles", "Multiple timelines", "Scientific concepts"]', '[{"name": "Gary W.", "rating": 5, "comment": "Mind-bending time travel puzzles!"}, {"name": "Nancy E.", "rating": 4, "comment": "Complex but fascinating."}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Alien Mothership', 'Sci-Fi', 'Medium', 'Industrial District', 60, 40.00, 'Escape before departure', 4.5, 6, '["Alien technology", "Spaceship interior", "Extraterrestrial puzzles", "Escape sequence"]', '[{"name": "Michelle A.", "rating": 4, "comment": "Great alien atmosphere."}, {"name": "Kevin S.", "rating": 5, "comment": "Felt like being on a real spaceship!"}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Cyberpunk City', 'Sci-Fi', 'Hard', 'Business District', 75, 45.00, 'Hack the corporate mainframe', 4.5, 6, '["Cyberpunk aesthetic", "Hacking puzzles", "Neon lighting", "Corporate espionage"]', '[{"name": "Tyler B.", "rating": 5, "comment": "Perfect cyberpunk atmosphere!"}, {"name": "Jessica M.", "rating": 4, "comment": "Great hacking challenges."}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Space Station Omega', 'Sci-Fi', 'Advanced', 'Airport Area', 80, 52.00, 'Prevent the reactor meltdown', 4.5, 6, '["Space station", "Nuclear reactor", "Emergency protocols", "Technical puzzles"]', '[{"name": "Daniel R.", "rating": 4, "comment": "Intense space station experience."}, {"name": "Carol L.", "rating": 5, "comment": "Great technical challenges!"}]', 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Adventure Theme Escape Rooms
('Pirate Ship Treasure', 'Adventure', 'Beginner', 'Waterfront', 45, 30.00, 'Find Captain Blackbeard''s gold', 4.5, 6, '["Pirate ship setting", "Treasure hunt", "Maritime puzzles", "Beginner friendly"]', '[{"name": "Emma J.", "rating": 5, "comment": "Perfect for beginners!"}, {"name": "Jack H.", "rating": 4, "comment": "Great pirate atmosphere."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Indiana Jones Temple', 'Adventure', 'Advanced', 'Historic District', 75, 45.00, 'Navigate the booby-trapped temple', 4.5, 6, '["Ancient temple", "Booby traps", "Archaeological puzzles", "Adventure movie feel"]', '[{"name": "Ryan C.", "rating": 5, "comment": "Felt like being in an Indiana Jones movie!"}, {"name": "Sarah D.", "rating": 4, "comment": "Great adventure puzzles."}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Jungle Expedition', 'Adventure', 'Medium', 'Tourist Area', 55, 35.00, 'Discover the lost civilization', 4.5, 6, '["Jungle setting", "Lost civilization", "Nature puzzles", "Exploration theme"]', '[{"name": "Mike F.", "rating": 4, "comment": "Great jungle atmosphere."}, {"name": "Lisa G.", "rating": 5, "comment": "Loved the exploration aspect!"}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Arctic Survival', 'Adventure', 'Hard', 'Suburbs', 70, 42.00, 'Escape the frozen wilderness', 4.5, 6, '["Arctic setting", "Survival challenges", "Cold weather effects", "Teamwork required"]', '[{"name": "Tom I.", "rating": 5, "comment": "Challenging survival experience!"}, {"name": "Rachel K.", "rating": 4, "comment": "Great teamwork required."}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Treasure Island', 'Adventure', 'Easy', 'Waterfront', 50, 32.00, 'Follow the pirate''s map', 4.5, 6, '["Treasure island", "Pirate map", "Beach setting", "Family friendly"]', '[{"name": "Amy L.", "rating": 4, "comment": "Great for families."}, {"name": "Chris M.", "rating": 5, "comment": "Fun treasure hunt!"}]', 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Fantasy Theme Escape Rooms
('Dragon''s Tower', 'Fantasy', 'Expert', 'Historic District', 80, 50.00, 'Rescue the princess from the dragon', 4.5, 6, '["Medieval fantasy", "Dragon encounter", "Princess rescue", "Magic elements"]', '[{"name": "Peter N.", "rating": 5, "comment": "Epic fantasy adventure!"}, {"name": "Helen O.", "rating": 4, "comment": "Great dragon effects."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Wizard''s Academy', 'Fantasy', 'Medium', 'University Area', 65, 42.00, 'Graduate from magic school', 4.5, 6, '["Magic school", "Spell casting", "Potion making", "Wizardry puzzles"]', '[{"name": "Sophie P.", "rating": 5, "comment": "Magical experience!"}, {"name": "James Q.", "rating": 4, "comment": "Great magic school theme."}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Enchanted Forest', 'Fantasy', 'Beginner', 'Tourist Area', 40, 28.00, 'Break the fairy tale curse', 4.5, 6, '["Enchanted forest", "Fairy tale elements", "Curse breaking", "Magical creatures"]', '[{"name": "Katie R.", "rating": 4, "comment": "Beautiful fairy tale setting."}, {"name": "Mark S.", "rating": 5, "comment": "Perfect for beginners!"}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Medieval Quest', 'Fantasy', 'Hard', 'Historic District', 75, 46.00, 'Retrieve the sacred artifact', 4.5, 6, '["Medieval setting", "Sacred quest", "Knight''s journey", "Ancient artifacts"]', '[{"name": "Laura T.", "rating": 5, "comment": "Epic medieval quest!"}, {"name": "David U.", "rating": 4, "comment": "Great medieval atmosphere."}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Fairy Kingdom', 'Fantasy', 'Easy', 'Residential Area', 45, 30.00, 'Help the fairy queen', 4.5, 6, '["Fairy kingdom", "Magical realm", "Fairy queen", "Whimsical puzzles"]', '[{"name": "Anna V.", "rating": 4, "comment": "Whimsical and fun."}, {"name": "Ben W.", "rating": 5, "comment": "Great for families!"}]', 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Thriller Theme Escape Rooms
('Escape the Killer', 'Thriller', 'Expert', 'Downtown', 60, 44.00, 'Survive the serial killer''s game', 4.5, 6, '["Serial killer theme", "Psychological thriller", "Survival horror", "Intense atmosphere"]', '[{"name": "Carlos X.", "rating": 5, "comment": "Incredibly intense experience!"}, {"name": "Diana Y.", "rating": 4, "comment": "Heart-pounding thriller."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Underground Bunker', 'Thriller', 'Advanced', 'Industrial District', 75, 48.00, 'Escape before the bomb explodes', 4.5, 6, '["Underground bunker", "Bomb defusal", "Time pressure", "Military setting"]', '[{"name": "Eric Z.", "rating": 4, "comment": "Great military bunker theme."}, {"name": "Fiona A.", "rating": 5, "comment": "Intense bomb defusal!"}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Kidnapper''s Den', 'Thriller', 'Hard', 'Suburbs', 55, 38.00, 'Break free from captivity', 4.5, 6, '["Kidnapping scenario", "Escape from captivity", "Psychological elements", "Survival theme"]', '[{"name": "Grace B.", "rating": 5, "comment": "Thrilling escape experience!"}, {"name": "Henry C.", "rating": 4, "comment": "Great psychological elements."}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Spy Mission', 'Thriller', 'Medium', 'Business District', 70, 42.00, 'Complete the covert operation', 4.5, 6, '["Spy theme", "Covert operations", "Espionage puzzles", "Secret agent"]', '[{"name": "Ian D.", "rating": 4, "comment": "Great spy atmosphere."}, {"name": "Julia E.", "rating": 5, "comment": "Felt like a real secret agent!"}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Historical Theme Escape Rooms
('Ancient Egypt', 'Historical', 'Medium', 'Historic District', 65, 40.00, 'Escape the pharaoh''s tomb', 4.5, 6, '["Ancient Egypt", "Pharaoh''s tomb", "Hieroglyphics", "Egyptian mythology"]', '[{"name": "Kelly F.", "rating": 5, "comment": "Amazing Egyptian atmosphere!"}, {"name": "Larry G.", "rating": 4, "comment": "Great historical details."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Viking Longship', 'Historical', 'Advanced', 'Waterfront', 70, 45.00, 'Survive the Norse adventure', 4.5, 6, '["Viking theme", "Norse mythology", "Longship setting", "Viking culture"]', '[{"name": "Monica H.", "rating": 4, "comment": "Great Viking atmosphere."}, {"name": "Nathan I.", "rating": 5, "comment": "Loved the Norse mythology!"}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Roman Gladiator', 'Historical', 'Hard', 'Entertainment District', 60, 42.00, 'Fight for your freedom', 4.5, 6, '["Roman Empire", "Gladiator arena", "Ancient Rome", "Combat challenges"]', '[{"name": "Olivia J.", "rating": 5, "comment": "Epic gladiator experience!"}, {"name": "Patrick K.", "rating": 4, "comment": "Great Roman setting."}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Wild West Saloon', 'Historical', 'Medium', 'Tourist Area', 55, 36.00, 'Solve the frontier mystery', 4.5, 6, '["Wild West", "Saloon setting", "Frontier life", "Western mystery"]', '[{"name": "Quinn L.", "rating": 4, "comment": "Great Wild West atmosphere."}, {"name": "Rosa M.", "rating": 5, "comment": "Loved the saloon setting!"}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Crime Theme Escape Rooms
('Bank Heist', 'Crime', 'Expert', 'Downtown', 75, 48.00, 'Pull off the perfect robbery', 4.5, 6, '["Bank robbery", "Heist planning", "Security systems", "Criminal mastermind"]', '[{"name": "Sam N.", "rating": 5, "comment": "Perfect heist experience!"}, {"name": "Tina O.", "rating": 4, "comment": "Great bank setting."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Prison Break', 'Crime', 'Advanced', 'Industrial District', 80, 45.00, 'Escape from maximum security', 4.5, 6, '["Prison escape", "Maximum security", "Inmate cooperation", "Jailbreak plan"]', '[{"name": "Uma P.", "rating": 4, "comment": "Intense prison atmosphere."}, {"name": "Victor Q.", "rating": 5, "comment": "Great escape planning!"}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Mafia Hideout', 'Crime', 'Hard', 'Business District', 65, 42.00, 'Infiltrate the crime family', 4.5, 6, '["Mafia theme", "Crime family", "Undercover operation", "Organized crime"]', '[{"name": "Wendy R.", "rating": 5, "comment": "Great mafia atmosphere!"}, {"name": "Xavier S.", "rating": 4, "comment": "Loved the crime family theme."}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Casino Theft', 'Crime', 'Medium', 'Entertainment District', 70, 44.00, 'Steal from the mob casino', 4.5, 6, '["Casino heist", "Mob casino", "Gambling theme", "High stakes"]', '[{"name": "Yolanda T.", "rating": 4, "comment": "Great casino atmosphere."}, {"name": "Zachary U.", "rating": 5, "comment": "High stakes excitement!"}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Zombie Theme Escape Rooms
('Zombie Apocalypse', 'Zombie', 'Hard', 'Industrial District', 60, 40.00, 'Survive the undead outbreak', 4.5, 6, '["Zombie outbreak", "Survival horror", "Undead enemies", "Apocalypse setting"]', '[{"name": "Alice V.", "rating": 5, "comment": "Terrifying zombie experience!"}, {"name": "Bob W.", "rating": 4, "comment": "Great survival elements."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Infected Lab', 'Zombie', 'Expert', 'Airport Area', 75, 46.00, 'Find the cure before it spreads', 4.5, 6, '["Zombie virus", "Laboratory setting", "Cure research", "Infection spread"]', '[{"name": "Cathy X.", "rating": 4, "comment": "Great lab atmosphere."}, {"name": "Derek Y.", "rating": 5, "comment": "Loved the scientific approach!"}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Zombie School', 'Zombie', 'Medium', 'University Area', 55, 38.00, 'Escape the infected campus', 4.5, 6, '["School setting", "Campus outbreak", "Student survival", "Educational theme"]', '[{"name": "Eva Z.", "rating": 5, "comment": "Great school zombie theme!"}, {"name": "Frank A.", "rating": 4, "comment": "Loved the campus setting."}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Prison Break Theme Escape Rooms
('Alcatraz Escape', 'Prison Break', 'Expert', 'Waterfront', 80, 50.00, 'Break out of the infamous prison', 4.5, 6, '["Alcatraz prison", "Famous escape", "Historical prison", "Maximum security"]', '[{"name": "George B.", "rating": 5, "comment": "Incredible Alcatraz recreation!"}, {"name": "Hannah C.", "rating": 4, "comment": "Great historical details."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('County Jail', 'Prison Break', 'Advanced', 'Downtown', 65, 42.00, 'Escape before your execution', 4.5, 6, '["County jail", "Execution countdown", "Time pressure", "Jailbreak plan"]', '[{"name": "Ivan D.", "rating": 4, "comment": "Intense time pressure."}, {"name": "Jenny E.", "rating": 5, "comment": "Great escape planning!"}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Underground Prison', 'Prison Break', 'Hard', 'Industrial District', 70, 45.00, 'Tunnel your way to freedom', 4.5, 6, '["Underground prison", "Tunnel escape", "Secret passages", "Underground setting"]', '[{"name": "Kelly F.", "rating": 5, "comment": "Great tunnel escape theme!"}, {"name": "Liam G.", "rating": 4, "comment": "Loved the underground setting."}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Pirate Theme Escape Rooms
('Captain''s Quarters', 'Pirate', 'Medium', 'Waterfront', 60, 38.00, 'Find the treasure map', 4.5, 6, '["Pirate ship", "Captain''s quarters", "Treasure map", "Maritime adventure"]', '[{"name": "Maya H.", "rating": 4, "comment": "Great pirate ship atmosphere."}, {"name": "Noah I.", "rating": 5, "comment": "Loved the treasure hunt!"}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Pirate''s Revenge', 'Pirate', 'Advanced', 'Historic District', 70, 44.00, 'Escape the cursed ship', 4.5, 6, '["Cursed pirate ship", "Supernatural elements", "Pirate curse", "Maritime mystery"]', '[{"name": "Olivia J.", "rating": 5, "comment": "Great cursed ship theme!"}, {"name": "Paul K.", "rating": 4, "comment": "Loved the supernatural elements."}]', 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Blackbeard''s Legacy', 'Pirate', 'Hard', 'Tourist Area', 65, 42.00, 'Claim the pirate''s inheritance', 4.5, 6, '["Blackbeard theme", "Pirate inheritance", "Historical pirate", "Treasure legacy"]', '[{"name": "Quinn L.", "rating": 4, "comment": "Great Blackbeard theme."}, {"name": "Rachel M.", "rating": 5, "comment": "Loved the historical elements!"}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Space Theme Escape Rooms
('Moon Base Alpha', 'Space', 'Advanced', 'Airport Area', 85, 52.00, 'Repair the lunar station', 4.5, 6, '["Moon base", "Lunar station", "Space repair", "Astronaut mission"]', '[{"name": "Sam N.", "rating": 5, "comment": "Amazing space station experience!"}, {"name": "Tara O.", "rating": 4, "comment": "Great lunar setting."}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Asteroid Mining', 'Space', 'Expert', 'Industrial District', 75, 48.00, 'Escape the mining facility', 4.5, 6, '["Asteroid mining", "Space mining", "Industrial space", "Mining facility"]', '[{"name": "Uma P.", "rating": 4, "comment": "Great mining facility theme."}, {"name": "Victor Q.", "rating": 5, "comment": "Loved the space industrial setting!"}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Galactic Patrol', 'Space', 'Medium', 'Business District', 60, 40.00, 'Stop the alien invasion', 4.5, 6, '["Space patrol", "Alien invasion", "Galactic defense", "Space combat"]', '[{"name": "Wendy R.", "rating": 5, "comment": "Great space patrol theme!"}, {"name": "Xavier S.", "rating": 4, "comment": "Loved the alien invasion story."}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Medieval Theme Escape Rooms
('Castle Siege', 'Medieval', 'Hard', 'Historic District', 75, 45.00, 'Defend the kingdom', 4.5, 6, '["Medieval castle", "Castle siege", "Kingdom defense", "Medieval warfare"]', '[{"name": "Yolanda T.", "rating": 4, "comment": "Great medieval castle theme."}, {"name": "Zachary U.", "rating": 5, "comment": "Epic castle defense!"}]', 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Knight''s Quest', 'Medieval', 'Advanced', 'Tourist Area', 70, 42.00, 'Prove your worth as a knight', 4.5, 6, '["Knight''s quest", "Medieval chivalry", "Knighthood trials", "Honor code"]', '[{"name": "Alice V.", "rating": 5, "comment": "Great knight''s quest theme!"}, {"name": "Bob W.", "rating": 4, "comment": "Loved the chivalry elements."}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Royal Court', 'Medieval', 'Medium', 'Uptown', 65, 40.00, 'Solve the palace intrigue', 4.5, 6, '["Royal court", "Palace intrigue", "Medieval politics", "Court mystery"]', '[{"name": "Cathy X.", "rating": 4, "comment": "Great royal court atmosphere."}, {"name": "Derek Y.", "rating": 5, "comment": "Loved the palace intrigue!"}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Steampunk Theme Escape Rooms
('Clockwork Factory', 'Steampunk', 'Expert', 'Industrial District', 80, 48.00, 'Fix the mechanical city', 4.5, 6, '["Steampunk factory", "Clockwork mechanisms", "Mechanical puzzles", "Industrial steampunk"]', '[{"name": "Eva Z.", "rating": 5, "comment": "Amazing steampunk atmosphere!"}, {"name": "Frank A.", "rating": 4, "comment": "Great mechanical puzzles."}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Airship Adventure', 'Steampunk', 'Advanced', 'Airport Area', 70, 45.00, 'Navigate the sky pirates', 4.5, 6, '["Steampunk airship", "Sky pirates", "Aerial adventure", "Victorian technology"]', '[{"name": "George B.", "rating": 4, "comment": "Great airship theme."}, {"name": "Hannah C.", "rating": 5, "comment": "Loved the sky pirate adventure!"}]', 'https://images.pexels.com/photos/1070945/pexels-photo-1070945.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Steam Engine', 'Steampunk', 'Hard', 'Downtown', 65, 42.00, 'Prevent the boiler explosion', 4.5, 6, '["Steam engine", "Boiler explosion", "Steam power", "Industrial danger"]', '[{"name": "Ivan D.", "rating": 5, "comment": "Great steam engine theme!"}, {"name": "Jenny E.", "rating": 4, "comment": "Loved the industrial setting."}]', 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'),

-- Western Theme Escape Rooms
('Saloon Showdown', 'Western', 'Medium', 'Tourist Area', 60, 38.00, 'Settle the score at high noon', 4.5, 6, '["Wild West saloon", "High noon showdown", "Western duel", "Frontier justice"]', '[{"name": "Kelly F.", "rating": 4, "comment": "Great Wild West atmosphere."}, {"name": "Liam G.", "rating": 5, "comment": "Loved the saloon setting!"}]', 'https://images.pexels.com/photos/2693529/pexels-photo-2693529.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Gold Rush', 'Western', 'Advanced', 'Historic District', 70, 44.00, 'Strike it rich in the mines', 4.5, 6, '["Gold rush", "Mining town", "Prospector life", "Western frontier"]', '[{"name": "Maya H.", "rating": 5, "comment": "Great gold rush theme!"}, {"name": "Noah I.", "rating": 4, "comment": "Loved the mining elements."}]', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=800'),
('Outlaw''s Hideout', 'Western', 'Hard', 'Suburbs', 65, 42.00, 'Escape the sheriff''s posse', 4.5, 6, '["Outlaw hideout", "Sheriff''s posse", "Western outlaws", "Frontier escape"]', '[{"name": "Olivia J.", "rating": 4, "comment": "Great outlaw theme."}, {"name": "Paul K.", "rating": 5, "comment": "Loved the chase element!"}]', 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=800');